version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=console
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=console
    ports:
      - "8082:3306"
  app:
    container_name: php73
    image: php_img:latest
    build:
      context: ./
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql